import express from "express";
import cors from "cors";
import helmet from "helmet";
import { env } from "./config/index";
import dishRouter from "./modules/dishes/dish.routes";
import orderRouter from "./modules/orders/order.routes";
import userRouter from "./modules/users/user.routes";
import chatRouter from "./modules/chat/chat.routes";
import employeeRouter from "./modules/employees/employee.routes";
import inventoryRouter from "./modules/inventory/inventory.routes";
import blogRouter from "./modules/blogs/blog.routes";
import eventRouter from "./modules/events/event.routes";
import payrollRouter from "./modules/payroll/payroll.routes";
import tableRouter from "./modules/tables/table.routes";
import analyticsRouter from "./modules/analytics/userBehavior.routes";
import complaintRouter from "./modules/complaints/complaint.routes";
import notificationRouter from "./modules/notifications/notification.routes";
import ingredientRouter from "./modules/ingredients/ingredient.routes";
import categoryDishRouter from "./modules/categoryDishes/categoryDish.routes";
import supplierRouter from "./modules/suppliers/supplier.routes";
import orderItemRouter from "./modules/orderItems/orderItem.routes";
import employeeShiftRouter from "./modules/employeeShifts/employeeShift.routes";
import reviewRouter from "./modules/reviews/review.routes";
import voucherRouter from "./modules/vouchers/voucher.routes";
import voucherUsageRouter from "./modules/voucherUsages/voucherUsage.routes";
import tableGroupRouter from "./modules/tableGroups/tableGroup.routes";
import eventBookingRouter from "./modules/eventBookings/eventBooking.routes";
import dishIngredientRouter from "./modules/dishIngredients/dishIngredient.routes";
import orderItemLogRouter from "./modules/orderItemLogs/orderItemLog.routes";
import { authMiddleware } from "./middleware/auth";
import swaggerUi from "swagger-ui-express";
import swaggerDoc from "./swagger/swagger.json";

const app = express();
app.use(helmet());
app.use(cors());
app.use(express.json({ limit: "1mb" }));

app.get("/health", (_req, res) => res.json({ status: "ok", env: env.nodeEnv }));

app.use(authMiddleware);
app.use("/api/dishes", dishRouter);
app.use("/api/orders", orderRouter);
app.use("/api/users", userRouter);
app.use("/api/chat", chatRouter);
app.use("/api/employees", employeeRouter);
app.use("/api/inventory", inventoryRouter);
app.use("/api/blogs", blogRouter);
app.use("/api/events", eventRouter);
app.use("/api/payroll", payrollRouter);
app.use("/api/tables", tableRouter);
app.use("/api/analytics", analyticsRouter);
app.use("/api/complaints", complaintRouter);
app.use("/api/notifications", notificationRouter);
app.use("/api/ingredients", ingredientRouter);
app.use("/api/category-dishes", categoryDishRouter);
app.use("/api/suppliers", supplierRouter);
app.use("/api/order-items", orderItemRouter);
app.use("/api/employee-shifts", employeeShiftRouter);
app.use("/api/vouchers", voucherRouter);
app.use("/api/voucher-usages", voucherUsageRouter);
app.use("/api/table-groups", tableGroupRouter);
app.use("/api/event-bookings", eventBookingRouter);
app.use("/api/dish-ingredients", dishIngredientRouter);
app.use("/api/order-item-logs", orderItemLogRouter);
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerDoc));

export default app;
